server:
  port: 8081
  servlet:
    context-path:
  tomcat:
    uri-encoding: UTF-8
    basedir: ./logs/tomcat
    max-threads: 2000
    min-spare-threads: 10
    accesslog:
      pattern: common
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      request-attributes-enabled: true
      rename-on-rotate: true
    max-http-form-post-size: 200MB
logging:
  level:
    root: INFO
    com.seekweb4.chat: DEBUG
  config: classpath:logback-spring.xml
spring:
  servlet:
    multipart:
      maxFileSize:  2048MB
      maxRequestSize: 2048MB
  devtools:
    restart:
      enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin
#      uri: mongodb://admin:admin@localhost:27017/admin
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/im?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/chat_platform_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      register-mbeans: true
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 300000           # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DataSourceHikariCP     # 连接池名字
      max-lifetime: 900000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1 FROM dual
      leak-detection-threshold: 30000
  redis:
    host: localhost
    port: 6379
    database: 5
    expireTime: 3600000 #单位秒
  mvc.servlet.load-on-startup: 1
  jmx:
    enabled: false
  # quartz任务配置
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            selectWithLockSQL: SELECT * FROM {0}LOCKS UPDLOCK WHERE LOCK_NAME = ?
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            tablePrefix: QRTZ_
            isClustered: false # 打开集群配置
            clusterCheckinInterval: 2000 # 设置集群检查间隔20s
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 17
            threadPriority: 8
            threadsInheritContextClassLoaderOfInitializingThread: true
# mybatis的配置
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations:
    - classpath*:com/*/*/modules/**/*Mapper.xml
    - classpath:/META-INF/admin-mybatis-mappings/*.xml
    - classpath:/META-INF/modeler-mybatis-mappings/*.xml
  type-aliases-package: com.seekweb4.chat.modules
  configuration-properties:
    prefix:
    boolValue: TRUE
    blobType: BLOB
#是否开启 swagger，生产环境请关闭
swagger:
  enable: false

#filePath: http://app.seekweb4.ai/
#httpsPath: http://app.seekweb4.ai/

filePath: http://api.seekweb4.ai/
httpsPath: http://api.seekweb4.ai/

#演示模式: 不能操作和保存的模块： sys
demoMode: false
#上传文件绝对路径, 路径中不允许包含“userfiles”
userfiles:
  basedir:       # 文件上传路径，可以留空
  allowedType: file  # 允许上传的文件类型， all, file ,image, audio, video, office
  extensions:
    all: all       # 允许上传所有类型文件
    file: 7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,jpeg,jpg,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,png,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip,apk,ipa,mpa       # 只允许上传安全文件（linux系统非可执行）
    image: gif,jpg,jpeg,bmp,png     # 只允许上传图片
    audio: CD,OGG,MP3,ASF,WMA,WAV,MP3PRO,RM,REAL,APE,MODULE,MIDI,VQF,mpa    # 只允许上传音频
    video: AVI,WMV,RM,RMVB,MPEG1,MPEG2,MPEG4(MP4),3GP,ASF,SWF,VOB,DAT,MOV,M4V,FLV,F4V,MKV,MTS,TS,MP4     # 只允许上传视频
    office: txt,xls,xlsx,xlsm,xltx,xltm,xlsb,xlam,doc,docx,docm,dotx,dotm,ppt,pptx,pptm,ppsx,ppsm,potx,potm,ppam     # 只允许上传office文件
#JWT access token过期时间（access过期时间，并不是指需要重新登录的超时时间，而是指需要刷新重新获取access token的时间，超时登录的时间是3*EXPIRE_TIME，即refresh token的有效时时间)
jwt.accessToken.expireTime: 86400000 # 24小时，单位毫秒
# 移动端接口JWT过期时间
jwt.appToken.expireTime: 604800000 # 7天，单位毫秒

#=======================================================================#
#===== plugin设置 =====#
#Plugin插件会读取该core和admin包下的基础类，如果修改了路径或者类名，请同步修改这里
#=======================================================================#
plugin:
  Page: com.seekweb4.chat.core.persistence.Page
  User: com.seekweb4.chat.modules.sys.entity.User
  Area: com.seekweb4.chat.modules.sys.entity.Area
  Office: com.seekweb4.chat.modules.sys.entity.Office
  UserUtils: com.seekweb4.chat.modules.sys.utils.UserUtils
# Socket配置
socket:
  # 监听端口
  port: 8888
  # 最大数量
  poolMax: 1000

im:
  admin:
    host: http://52.8.49.37:18080
    password: fyhKop-3kanti-hatzox
# 文件上传配置
config:
  accessory:
    type: aws    #local, aliyun, minIO, qcloud, qiniuyun, aws
    baseDir: file
    local: #本地存储
      location: /accessory
    aws: #亚马逊S3
      baseDir: file
      region: us-west-1
#      accessKey: AKIAXQ2N3G6SQUVUX45O
#      secretKey: 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
      endpoint: https://s3.us-west-1.amazonaws.com
      bucketName: us-web4x6
      accessUrl: https://d2ixzsnmawz3gt.cloudfront.net
      cdnDomain: static.seekweb4.net


# 用户ID号和靓号前缀配置
user:
  idno:
    prefix-m: true  # 是否在idno和lianghao前面添加M前缀，true表示添加，false表示不添加

asset:
  appId: im
  privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAL8f5eKXfg/6PcXhYeOdqA4naCgoVbM8uzV6Lk8JVRH5bFzygfAUXGCHvzfYOPiZgIqtBpUh5M3SqPIT4Y9l0zlEvxGY+QruqOILtMmTh4c/bs7LKzqoqO02UpN+cL3t50hH6cXoFzkCjmZLibsv3Le0RisoMTzwMf6DHxbz6dyjAgMBAAECgYBDe5vL2fmk4pKVH/NUTwJbnQZlx3gbBUKEq1NWjNEAu7TLTMUcY9QKMWQO78WN4YVFcbp1RbZoBg2pC+QEoctmPOy6Jw/7gpKNVpp+0yDWKtoSwjmD0iyfLrasdp8S70w8FXopGlFc+/E3Wg255YF7CJPipF3R5QbNppr1ruTEoQJBAN/d6TaqdOqQJDljULcO6BTuMuH9h/Z+D5qpzxmGCW7Cxx64X06plbUxN0SgGN/ZMDVdRbnN1d0pz4OTpWROjq0CQQDajtvJFOWNst+eGi9iYfM/vajUSdHlt3DBKiuTkF5mSC3FPwvVGPJSj7pMHIZagixyIf2LxEpStBMPNAq+ABKPAkEAnxoGsixI9Z/FruePqNo2RRHZJdXa+Gs1SdVfc6NYNtjFTWb5jV1nIaQ9xE8H/qdL5NFKSbgpQ4qAieG4DObr7QJADZs3M52JbPjl0wHuUUGn0yALkqvF1XdGHcByVg120wdLUixKoEmdTGaGQpbEBn50JebX0gu2VM/BIAEtaga3IQJALGQT5PI8pTDMNTiKr5XBmeM8dZWlWc1CXKHv2K8bxW6O5WmITDLNShbeZQu8YhdtSy1yM6fYj/xWUgeULSP+yw==
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/H+Xil34P+j3F4WHjnagOJ2goKFWzPLs1ei5PCVUR+Wxc8oHwFFxgh7832Dj4mYCKrQaVIeTN0qjyE+GPZdM5RL8RmPkK7qjiC7TJk4eHP27Oyys6qKjtNlKTfnC97edIR+nF6Bc5Ao5mS4m7L9y3tEYrKDE88DH+gx8W8+ncowIDAQAB
  wxPayUrl: https://www.web4x.net/
#  wxPayUrl: https://hcadmin.web4x.cn # web4x链桥后台测试环境

withdrawal:
  appId: im
  privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAOznQnLhH6eyrJ7ihfy5hKULa41nGfovnZy8JVIxAHC3htFjW2QU+tAi9I+/HYTV+K27RArgtadoAIMvR4WOhKPbiRF/X810NxbxG1YkDt3eY8nTKtj/u2bcIguIEAJKmZK4QmGpXKmP3tdrOGvjHKQXKKrYGsRdhaI87l9kVeFtAgMBAAECgYBdgfqMdaeU/cV9AVR5qJBexN8y9Rsf0WOY1fq1MnpGA2rHgzwziMRnGyUFCB6SrBJ4II5+7KtG5JovLZ5BbTuU3ylfKUZWSl0rPBFP8N5uNGJ4623aKapCX1oo++l2vGpcFhQZyu379X+RRdabxgkFoDfc02hyGPoOaUdGG6LN0QJBAO0N5lf/tkJpjoyN+Vj273ZLv1ZSDUd4BAUvz81nR6P5f0T1a4RrAzKQ7J655JCFxpHSawC4Ka5GYDaZNmCmXmsCQQD/1kWH/SunQjccgEJyhF2I+5sJEjf9u1R+Y1N1wYXnfsePe9UFUThwvt31i7HUx0gm8zxJLmA9/b/z/OPyxgWHAkBnlFc9xEIDKtRanf6B3QQtEFP+h8O9orc+/PEzsxkekPoHS6U7KvcutRxvDpLMg2eMeADBQ7cSqzWHJdMY0BkZAkEAtkCPsevCEFoUZqJcM7Zl57LN5C1tY7zy2UKq7wVY/ewMAARIYYxVt8PQ3R6SJbF9jfnTJZL7Ds5Y01iBjq5QuwJAYu+mIIbpma1+4zlCDAHwtJze392SaNPW4AdQppShn/FHS0yHN4pUIs20nyI7LiKN0f1iQUxn7mXpVw3NWvCSUQ==
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDs50Jy4R+nsqye4oX8uYSlC2uNZxn6L52cvCVSMQBwt4bRY1tkFPrQIvSPvx2E1fitu0QK4LWnaACDL0eFjoSj24kRf1/NdDcW8RtWJA7d3mPJ0yrY/7tm3CILiBACSpmSuEJhqVypj97Xazhr4xykFyiq2BrEXYWiPO5fZFXhbQIDAQAB
  wxPayUrl: https://bscapi.web4x.cn